### ISSUE TITLE
UserArray array is not initialized globally

### ISSUE THREAD

**Issue by coremedic** [dahvidschloss/CRASH#1]
The UserArray array is not initialized as a global variable, as a result the users info cannot be added to the array. Its a null array indexing error. 

The fix is simple,
Replace this line:
```ps
$UserArray = @{}
```
https://github.com/dahvidschloss/ADGenny/blob/main/ADGenny.ps1#L9
With this:
```ps
$global:UserArray = @{}
```

**Comment by dahvidschloss** [comment]
Added to update for v1.1  Will make it in the next release
